apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: first-service
      port:
        number: 3000
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: first-service
              port:
                number: 3000
        - path: /first
          pathType: Prefix
          backend:
            service:
              name: first-service
              port:
                number: 3000
        - path: /second
          pathType: Prefix
          backend:
            service:
              name: second-service
              port:
                number: 3000